name: Production Deployment

on:
  workflow_run:
    workflows: ["Pre-Production Deployment"]
    types:
      - completed

jobs:
  deploy_to_prod:
    name: Deploy to Production
    runs-on: ubuntu-latest
    if: github.event.workflow_run.event == 'workflow_run' && needs.deploy_to_preprod.result == 'success'

    steps:
    - name: Manual approval
      id: approval
      run: echo "Approve the deployment by commenting '/approve' on the workflow run."

    - name: Check for approval
      run: |
        if [[ "${{ steps.approval.outputs.result }}" == "/approve" ]]; then
          echo "Deployment approved. Proceeding with production deployment."
        else
          echo "Deployment not approved. Skipping production deployment."
          exit 0
        fi

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'

    - name: Install Railway CLI
      run: npm install -g @railway/cli

    - name: Deploy to Railway Production
      run: |
        # Set the RAILWAY_TOKEN environment variable
        export RAILWAY_TOKEN=${{ secrets.RAILWAY_API_TOKEN_PROD }}

        # Run the production deployment command for your services
        railway up -e production -s myaichat
        railway up -e production -s loader.myaichat
        railway up -e production -s api.myaichat
        railway up -e production -s dashboard.myaichat
        railway up -e production -s chatbot.myaichat
